tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "kyoshidajp/ghkw"
tap "sanemat/font"
tap "vapor/tap"
tap "yutomizutani/jc"
brew "autojump"
brew "automake"
brew "awscli"
brew "bash"
brew "bitrise"
brew "carthage"
brew "cmake"
brew "direnv"
brew "ffmpeg"
brew "gibo"
brew "git"
brew "go"
brew "hardlink-osx"
brew "imagemagick"
brew "ios-sim"
brew "jq"
brew "libgit2"
brew "libressl"
brew "mas"
brew "mergepbx"
brew "mysql"
brew "ninja"
brew "nodebrew"
brew "nvm"
brew "peco"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "swiftlint"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "xcodegen"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "kyoshidajp/ghkw/ghkw"
brew "sanemat/font/ricty"
brew "vapor/tap/vapor"
cask "alfred"
cask "appcleaner"
cask "aquaskk"
cask "atom"
cask "chromedriver"
cask "cyberduck"
cask "dbeaver-community"
cask "docker"
cask "google-chrome"
cask "hammerspoon"
cask "java"
cask "keepingyouawake"
cask "macdown"
cask "ngrok"
cask "sequel-pro-nightly"
cask "skitch"
cask "skype"
cask "sleipnir"
cask "the-unarchiver"
cask "vagrant"
cask "visual-studio-code"
mas "Alfred", id: 405843582
mas "CotEditor", id: 1024640650
mas "Filedrop", id: 659443478
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Octotree Pro", id: 1457450145
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
